In [3]:
import numpy as np

In [12]:
def calculate_levenshtein_distance(source, target):
    
    m = len(source)
    n = len(target)
    del_cost = 1
    ins_cost = 1
    rep_cost = 2
    
    D = np.zeros((m+1, n+1))
    
    # fill in the first column
    for col in range(1, m+1):
        D[0,col] = D[0,col-1] + del_cost
        
    # fill in the first row
    for row in range(1, n+1):
        D[row,0] = D[row-1,0] + ins_cost
        
    # fill the rest of the table
    for row in range(1, m+1):
        for col in range(1, n+1):
            rep_temp = rep_cost
            
            if source[row-1] == target[col-1]:
                rep_temp = 0
                
            D[row, col] = min([D[row,col-1] + del_cost, D[row-1,col] + ins_cost, D[row-1,col-1] + rep_temp])
                
    min_edit_dist = D[m,n]
    
    return D, min_edit_dist

In [14]:
source = 'play'
target = 'stay'
D, min_edit_dist = calculate_levenshtein_distance(source, target)

print('Source:', source)
print('Target:', target)
print('Minimum number of edit operations:', min_edit_dist)
print(D)

Source: play
Target: stay
Minimum number of edit operations: 4.0
[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 4. 5.]
 [4. 5. 6. 5. 4.]]
